onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_cluster_group/WRITE_COUNT_SIZE
add wave -noupdate /tb_cluster_group/weight_values_per_filter
add wave -noupdate /tb_cluster_group/WEIGHT_VALS_PER_FILTER
add wave -noupdate /tb_cluster_group/WEIGHT_SRAM_ADDRESS_SIZE
add wave -noupdate /tb_cluster_group/WEIGHT_SIZE
add wave -noupdate /tb_cluster_group/weight_router2_data_out_sel
add wave -noupdate /tb_cluster_group/weight_router2_data_in_sel
add wave -noupdate /tb_cluster_group/weight_router1_data_out_sel
add wave -noupdate /tb_cluster_group/weight_router1_data_in_sel
add wave -noupdate /tb_cluster_group/weight_router0_data_out_sel
add wave -noupdate /tb_cluster_group/weight_router0_data_in_sel
add wave -noupdate /tb_cluster_group/weight_GLB_write_en
add wave -noupdate /tb_cluster_group/weight_GLB_write_done_fb
add wave -noupdate /tb_cluster_group/weight_GLB_write_done_ctrl
add wave -noupdate /tb_cluster_group/weight_GLB_write_addr
add wave -noupdate /tb_cluster_group/weight_GLB_read_en_2
add wave -noupdate /tb_cluster_group/weight_GLB_read_en_1
add wave -noupdate /tb_cluster_group/weight_GLB_read_en_0
add wave -noupdate /tb_cluster_group/weight_GLB_read_done_2
add wave -noupdate /tb_cluster_group/weight_GLB_read_done_1
add wave -noupdate /tb_cluster_group/weight_GLB_read_done_0
add wave -noupdate /tb_cluster_group/weight_GLB_read_addr_2
add wave -noupdate /tb_cluster_group/weight_GLB_read_addr_1
add wave -noupdate /tb_cluster_group/weight_GLB_read_addr_0
add wave -noupdate /tb_cluster_group/weight_GLB_data_out_valid_2
add wave -noupdate /tb_cluster_group/weight_GLB_data_out_valid_1
add wave -noupdate /tb_cluster_group/weight_GLB_data_out_valid_0
add wave -noupdate /tb_cluster_group/weight_GLB_data_out_ready_2
add wave -noupdate /tb_cluster_group/weight_GLB_data_out_ready_1
add wave -noupdate /tb_cluster_group/weight_GLB_data_out_ready_0
add wave -noupdate /tb_cluster_group/weight_GLB_data_out_2
add wave -noupdate /tb_cluster_group/weight_GLB_data_out_1
add wave -noupdate /tb_cluster_group/weight_GLB_data_out_0
add wave -noupdate /tb_cluster_group/weight_GLB_data_in_valid
add wave -noupdate /tb_cluster_group/weight_GLB_data_in_ready
add wave -noupdate /tb_cluster_group/weight_GLB_data_in
add wave -noupdate /tb_cluster_group/weight_columns
add wave -noupdate /tb_cluster_group/weight_column_counter
add wave -noupdate /tb_cluster_group/WEIGHT_COLS
add wave -noupdate /tb_cluster_group/w2_pe2_v
add wave -noupdate /tb_cluster_group/w2_pe2_d
add wave -noupdate /tb_cluster_group/w2_pe1_v
add wave -noupdate /tb_cluster_group/w2_pe1_d
add wave -noupdate /tb_cluster_group/w2_pe0_v
add wave -noupdate /tb_cluster_group/w2_pe0_d
add wave -noupdate /tb_cluster_group/w2_horiz_v
add wave -noupdate /tb_cluster_group/w2_horiz_d
add wave -noupdate /tb_cluster_group/w2_glb_in_ready
add wave -noupdate /tb_cluster_group/w1_pe2_v
add wave -noupdate /tb_cluster_group/w1_pe2_d
add wave -noupdate /tb_cluster_group/w1_pe1_v
add wave -noupdate /tb_cluster_group/w1_pe1_d
add wave -noupdate /tb_cluster_group/w1_pe0_v
add wave -noupdate /tb_cluster_group/w1_pe0_d
add wave -noupdate /tb_cluster_group/w1_horiz_v
add wave -noupdate /tb_cluster_group/w1_horiz_d
add wave -noupdate /tb_cluster_group/w1_glb_in_ready
add wave -noupdate /tb_cluster_group/w0_pe2_v
add wave -noupdate /tb_cluster_group/w0_pe2_d
add wave -noupdate /tb_cluster_group/w0_pe1_v
add wave -noupdate /tb_cluster_group/w0_pe1_d
add wave -noupdate /tb_cluster_group/w0_pe0_v
add wave -noupdate /tb_cluster_group/w0_pe0_d
add wave -noupdate /tb_cluster_group/w0_horiz_v
add wave -noupdate /tb_cluster_group/w0_horiz_d
add wave -noupdate /tb_cluster_group/w0_glb_in_ready
add wave -noupdate /tb_cluster_group/unique_values_per_cluster_per_cycle
add wave -noupdate /tb_cluster_group/unique_values_per_cluster
add wave -noupdate /tb_cluster_group/UNIQUE_VAL_PER_CYC
add wave -noupdate /tb_cluster_group/UNIQUE_VAL_PER_CLUSTER
add wave -noupdate /tb_cluster_group/turn_on
add wave -noupdate /tb_cluster_group/top_input_mode
add wave -noupdate /tb_cluster_group/top_filter_mode
add wave -noupdate /tb_cluster_group/rst
add wave -noupdate /tb_cluster_group/read_PEs_psum
add wave -noupdate /tb_cluster_group/r
add wave -noupdate /tb_cluster_group/psum_write_addr_shadow
add wave -noupdate /tb_cluster_group/psum_stream_start
add wave -noupdate /tb_cluster_group/psum_stream_done
add wave -noupdate /tb_cluster_group/psum_south_v
add wave -noupdate /tb_cluster_group/psum_south_d
add wave -noupdate /tb_cluster_group/PSUM_SIZE
add wave -noupdate /tb_cluster_group/psum_router3_data_out_sel
add wave -noupdate /tb_cluster_group/psum_router3_data_in_sel
add wave -noupdate /tb_cluster_group/psum_router2_data_out_sel
add wave -noupdate /tb_cluster_group/psum_router2_data_in_sel
add wave -noupdate /tb_cluster_group/psum_router1_data_out_sel
add wave -noupdate /tb_cluster_group/psum_router1_data_in_sel
add wave -noupdate /tb_cluster_group/psum_router0_data_out_sel
add wave -noupdate /tb_cluster_group/psum_router0_data_in_sel
add wave -noupdate /tb_cluster_group/psum_pe_out_v
add wave -noupdate /tb_cluster_group/psum_pe_out_d
add wave -noupdate /tb_cluster_group/psum_pe_in_valid
add wave -noupdate /tb_cluster_group/psum_pe_in_ready
add wave -noupdate /tb_cluster_group/psum_pe_in
add wave -noupdate /tb_cluster_group/psum_GLB_write_en
add wave -noupdate /tb_cluster_group/psum_GLB_write_done
add wave -noupdate /tb_cluster_group/psum_GLB_start_address
add wave -noupdate /tb_cluster_group/psum_glb_out_valid
add wave -noupdate /tb_cluster_group/psum_glb_out
add wave -noupdate /tb_cluster_group/psum_glb_in_ready
add wave -noupdate /tb_cluster_group/psum_GLB_depth
add wave -noupdate /tb_cluster_group/PSUM_ADDRESS_SIZE
add wave -noupdate /tb_cluster_group/PE_mode
add wave -noupdate /tb_cluster_group/mac_start
add wave -noupdate /tb_cluster_group/mac_done_counter
add wave -noupdate /tb_cluster_group/mac_done
add wave -noupdate /tb_cluster_group/load_PEs_weight_done
add wave -noupdate /tb_cluster_group/load_PEs_weight
add wave -noupdate /tb_cluster_group/load_PEs_iact_done
add wave -noupdate /tb_cluster_group/load_PEs_iact
add wave -noupdate /tb_cluster_group/INPUT_MODE
add wave -noupdate /tb_cluster_group/iact_write_addr_shadow
add wave -noupdate /tb_cluster_group/iact_tb_valid
add wave -noupdate /tb_cluster_group/iact_tb_data
add wave -noupdate /tb_cluster_group/IACT_SRAM_ADDRESS_SIZE
add wave -noupdate /tb_cluster_group/IACT_SIZE
add wave -noupdate /tb_cluster_group/iact_router2_PE_sel
add wave -noupdate /tb_cluster_group/iact_router2_PE_choice
add wave -noupdate /tb_cluster_group/iact_router2_Multicast_mode
add wave -noupdate /tb_cluster_group/iact_router2_data_out_sel
add wave -noupdate /tb_cluster_group/iact_router2_data_in_sel
add wave -noupdate /tb_cluster_group/iact_router1_PE_sel
add wave -noupdate /tb_cluster_group/iact_router1_PE_choice
add wave -noupdate /tb_cluster_group/iact_router1_Multicast_mode
add wave -noupdate /tb_cluster_group/iact_router1_data_out_sel
add wave -noupdate /tb_cluster_group/iact_router1_data_in_sel
add wave -noupdate /tb_cluster_group/iact_router0_PE_sel
add wave -noupdate /tb_cluster_group/iact_router0_PE_choice
add wave -noupdate /tb_cluster_group/iact_router0_Multicast_mode
add wave -noupdate /tb_cluster_group/iact_router0_data_out_sel
add wave -noupdate /tb_cluster_group/iact_router0_data_in_sel
add wave -noupdate /tb_cluster_group/iact_next_ofmap_col
add wave -noupdate /tb_cluster_group/iact_GLB_write_en
add wave -noupdate /tb_cluster_group/iact_GLB_write_done
add wave -noupdate /tb_cluster_group/iact_GLB_start_write_address
add wave -noupdate /tb_cluster_group/iact_GLB_start_read_address_port2
add wave -noupdate /tb_cluster_group/iact_GLB_start_read_address_port1
add wave -noupdate /tb_cluster_group/iact_GLB_start_read_address_port0
add wave -noupdate /tb_cluster_group/iact_glb_ready_w
add wave -noupdate /tb_cluster_group/iact_GLB_read_en
add wave -noupdate /tb_cluster_group/iact_column_done_flag
add wave -noupdate /tb_cluster_group/iact_2_GLB_data_in_valid
add wave -noupdate /tb_cluster_group/iact_2_GLB_data_in_ready
add wave -noupdate /tb_cluster_group/iact_2_GLB_data_in
add wave -noupdate /tb_cluster_group/iact_1_GLB_data_in_valid
add wave -noupdate /tb_cluster_group/iact_1_GLB_data_in_ready
add wave -noupdate /tb_cluster_group/iact_1_GLB_data_in
add wave -noupdate /tb_cluster_group/iact_0_GLB_data_in_valid
add wave -noupdate /tb_cluster_group/iact_0_GLB_data_in_ready
add wave -noupdate /tb_cluster_group/iact_0_GLB_data_in
add wave -noupdate /tb_cluster_group/FILTER_MODE
add wave -noupdate /tb_cluster_group/cycles_per_iact_col
add wave -noupdate /tb_cluster_group/CYCLES_PER_IACT_COL
add wave -noupdate /tb_cluster_group/CLK_PERIOD
add wave -noupdate /tb_cluster_group/clk
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {299999209 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {299999050 ps} {300000050 ps}
